# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
lang: no
title: IN2000
email: geira@met.no
description: Kursmateriale for IN2000 (Software Engineering med Prosjektarbeid)
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
#logo: "/images/Met_RGB_Horisontal_ENG_Negativ_crop.png"
favicon_ico: "/images/met_favicon.ico"
color_scheme: met
aux_links:
  #Template Repository: https://github.com/just-the-docs/just-the-docs-template
  #Repository: https://github.com/metno/in2000/

# Build settings
markdown: kramdown
#theme: minima
#theme: jekyll-theme-minimal
theme: just-the-docs
plugins:
  - jekyll-feed

callouts:
  warning:
    title: Advarsel
    color: red
  note:
    title: "Nota bene"
    color: blue
